### ISSUE TITLE
Since changing domain preference, cannot authenticate

### ISSUE THREAD

**Issue by TeoTwawki** [ivantsov/yandex-mail-notifier#53]
changed to .com and now addon never sees account as authenticated. tried to change back, still cannot authenticate. I have logged out and back in, have reloaded, have logged in on multiple yandex domain.. Nothing works. All started when I changed from .ru to .com

Browser: Firefox 54.0.1 (64 bit)
Addon version: v4.2.1

**Comment by ivantsov** [comment]
Hey @TeoTwawki, it works for me on FF55 (64 bit), MacOS, extension v4.2.1
Can you try to update your browser? Maybe reinstalling the extension help.

**Comment by TeoTwawki** [comment]
Oddly my firefox install insisted it was up to date.. So I manually ran the installer to update it. Proof I am not crazy and it is now updated:

**before**
![before](https://user-images.githubusercontent.com/6871475/29152534-ea948a6c-7d55-11e7-84f3-55f3d07c3925.jpg)

**after**
![after](https://user-images.githubusercontent.com/6871475/29152536-ee7741c4-7d55-11e7-8976-690a2ba6d1e5.jpg)


Tried reinstalling as well. Disabled all other addons, still says not authenticated. Tried completely removing the notifier and reinstalling it..Still says unauthenticated. Logged out everything cleared history and cache then logged back in..still not authenticated. I don't understand why this broke. It was working until I changed domain and now it won't go back. The first thing I tried was to change it back to .ru and logged in from mail.yandex.ru - that didn't work either, obviously.

If its working for you something had to be different on my system. This is a brand new setup though, just installed windows7 ultimate + firefox *2 days ago* and haven't even had time to ruin it yet. 😕

**Comment by ivantsov** [comment]
@TeoTwawki have you tried it out on Chrome?

**Comment by TeoTwawki** [comment]
Chrome version appears to be bug free.

**Comment by ivantsov** [comment]
If you have an ability to test the extension on another machine on Firefox - it would be great though. Otherwise, I don't have any idea so far what could cause such behavior :(

**Comment by TeoTwawki** [comment]
I have a laptop I can go install to.

May be awhile before I have free time though.

**Comment by ivantsov** [comment]
Hey @TeoTwawki did you manage to check out the assumption?

**Comment by ivantsov** [comment]
Hi @TeoTwawki, I'm gonna close this issue as there's no any activity. If the problem still exists - don't hesitate to reopen.

**Comment by TeoTwawki** [comment]
yeah sorry just have had no free time. when I can I'll get back to you.
