### ISSUE TITLE
Add multiple account support

### ISSUE THREAD

**Issue by xKeiro** [ivantsov/yandex-mail-notifier#54]
It would be so nice if you would add multiple account support to the notifier, I love how seamless you can switch between mail account in Yandex mail, but not getting notification from all of my accounts is quite the downer.

**Comment by ivantsov** [comment]
Actually I don't have this feature in plans for the following reasons:

- it's a very time-consuming feature in terms of implementation
- unfortunately not a lot of people are ready to support the project but rather complain about something not working; atm only 4 users made a donation which is nothing compare to ~4k active users every day
 
Thus I'm not gonna implement this feature in the near future, at least until users start supporting the project more actively or I see a real need in it.

However, I'm always glad to see a PR from outside ;)

**Comment by xKeiro** [comment]
Understandable, thanks for the reply!
