### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by Floyd77** [ivantsov/yandex-mail-notifier#69]
I get this error running you extension in Firefox Quantum:

![imagen](https://user-images.githubusercontent.com/11430884/33330863-4e8c58c2-d460-11e7-9613-2168cb970ced.png)

I tried login to my account with yandex.com and yandex.ru domain. Same result. Also, I saw the version you uploaded to AMO is not the latest (4.4.0).

Thanks a lot!

Update: I used the debugger and the problem is I have the [Tracking Protection](https://support.mozilla.org/en-US/kb/tracking-protection
) enabled.

I don't want to disable this feature, is there a workaround for this?

**Comment by ivantsov** [comment]
Hey @Floyd77, unfortunately I don't have time to investigate the issue now. But I'm glad that you found a root cause, and for now I can suggest you using this workaround.

**Comment by mpred04** [comment]
Firefox 69, seems like the issue is still present

**Comment by ivantsov** [comment]
Sorry, but I'm not gonna maintain the extension anymore.
