### ISSUE TITLE
None of the action buttons next to letters seem to work

### ISSUE THREAD

**Issue by mpred04** [ivantsov/yandex-mail-notifier#71]
![1](https://user-images.githubusercontent.com/7307115/64914120-4f0db080-d755-11e9-9182-df43ca5360bf.gif)

**Comment by and-semakin** [comment]
Probably Yandex.Mail has changed some API logic and now the buttons are completely useless.

**Comment by ivantsov** [comment]
Sorry, but I'm not gonna maintain the extension anymore.
